### ISSUE TITLE
E73-2G4M08S1C+MPU6500+QMC5883L

### ISSUE THREAD

**Issue by 01Space** [ysoldak/HeadTracker#15]
Hi，
Can you add firmware support for e73-2g4m08s1c + mpu6500 + qmc5883l board?
Others have developed a head tracker using ESP + mpu9250 with lower cost.
https://github.com/ScrumPilot616/HeadTracker

**Comment by ysoldak** [comment]
No. I don't have the hardware mentioned and cost was never the priority.
Zero configuration, small size, minimum soldering and ease to flash new versions -- these are the priorities of this project.
